server:
  port: 8080
spring:
  application:
    name: tableDiff
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.20.31.41:33061/increment?serverTimezone=UTC&characterEncoding=utf8&allowLoadLocalInfile=true&rewriteBatchedStatements=true
    username: root
    password: jgfw.123
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 600000
      # main set
      timeBetweenEvictionRunsMillis: 600000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filter:
        slf4j:
          enabled: true
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: true
      # set stat-view-servlet
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      # set web-stat-filter
      web-stat-filter:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.tbfeng.tabledif.domian.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl